// ─── REVISION SCHEDULE ──────────────────────────────────────────────────────
// Each revision is relative to the PREVIOUS revision (or study date for R1)
const REV_SCHEDULE = [
  { key: 'r1', label: 'R1', desc: '+1 day',    days: 1  },
  { key: 'r2', label: 'R2', desc: '+2 days',   days: 2  },
  { key: 'r3', label: 'R3', desc: '+4 days',   days: 4  },
  { key: 'r4', label: 'R4', desc: '+7 days',   days: 7  },
  { key: 'r5', label: 'R5', desc: '+10 days',  days: 10 },
  { key: 'r6', label: 'R6', desc: '+14 days',  days: 14 },
  { key: 'r7', label: 'R7', desc: '+18 days',  days: 18 },
  { key: 'r8', label: 'R8', desc: '+21 days',  days: 21 },
];

// ─── STUDY PLAN ─────────────────────────────────────────────────────────────
const STUDY_PLAN = {
  startDate: '2026-03-22',
  examDate:  '2026-07-26',
  graceDays: 5,
  phases: [
    {
      id: 'phase1', label: 'Phase 1', days: [1, 49], color: '#8B5E3C',
      desc: 'Science · Bihar Special · Ancient · Medieval · Modern History · Current Affairs Jul 2025–Apr 2026',
      sections: ['science', 'bihar', 'ancient', 'medieval', 'modern']
    },
    {
      id: 'phase2', label: 'Phase 2', days: [50, 74], color: '#5C6E4A',
      desc: 'Polity · Geography · Current Affairs May–Jun 2026',
      sections: ['polity']
    },
    {
      id: 'phase3', label: 'Phase 3', days: [75, 90], color: '#4A5C6E',
      desc: 'Economy · Maths/Reasoning · Current Affairs up to date',
      sections: ['bihar', 'maths']
    }
  ]
};

// ─── SECTIONS META ──────────────────────────────────────────────────────────
const SECTIONS_META = {
  science:  { label: 'General Science',    range: 'S1–S20', color: '#7B6B52' },
  ancient:  { label: 'Ancient India',      range: '1–20',   color: '#8B5E3C' },
  medieval: { label: 'Medieval India',     range: '21–40',  color: '#6B5B3E' },
  modern:   { label: 'Modern India',       range: '41–60',  color: '#5C6E4A' },
  polity:   { label: 'Polity + Geography', range: '61–90',  color: '#4A6B5C' },
  bihar:    { label: 'Bihar + Economics',  range: '91–110', color: '#7A5C4A' },
  maths:    { label: 'Maths + Reasoning',  range: '111–120',color: '#5C5A7A' },
};

// ─── 120 + 20 SCIENCE DAYS DATA ─────────────────────────────────────────────
const DAYS_DATA = [
  {id:'s1',  sec:'science', topic:'Matter, Sorting Materials'},
  {id:'s2',  sec:'science', topic:'Light, Shadows, Electricity Basics'},
  {id:'s3',  sec:'science', topic:'Living / Non-Living, Body Movement'},
  {id:'s4',  sec:'science', topic:'Food: Sources, Components'},
  {id:'s5',  sec:'science', topic:'Heat, Acids & Bases'},
  {id:'s6',  sec:'science', topic:'Light, Electric Current'},
  {id:'s7',  sec:'science', topic:'Weather, Wind, Water'},
  {id:'s8',  sec:'science', topic:'Crop Production, Microorganisms'},
  {id:'s9',  sec:'science', topic:'Coal, Petroleum, Combustion'},
  {id:'s10', sec:'science', topic:'Cell Structure, Reproduction'},
  {id:'s11', sec:'science', topic:'Force, Friction, Sound'},
  {id:'s12', sec:'science', topic:'Matter — States, Changes'},
  {id:'s13', sec:'science', topic:'Atoms, Molecules, Structure'},
  {id:'s14', sec:'science', topic:'Motion, Force, Laws'},
  {id:'s15', sec:'science', topic:'Work, Energy, Sound'},
  {id:'s16', sec:'science', topic:'Life Processes, Control'},
  {id:'s17', sec:'science', topic:'Heredity, Evolution'},
  {id:'s18', sec:'science', topic:'Light, Electricity, Magnetic'},
  {id:'s19', sec:'science', topic:'Carbon Compounds, Metals'},
  {id:'s20', sec:'science', topic:'Test Science NCERT'},
  {id:1,  sec:'ancient', topic:'Sources of History + Prehistoric Period'},
  {id:2,  sec:'ancient', topic:'Palaeolithic and Mesolithic Age'},
  {id:3,  sec:'ancient', topic:'Neolithic and Chalcolithic Age'},
  {id:4,  sec:'ancient', topic:'Indus Valley: Town Planning'},
  {id:5,  sec:'ancient', topic:'Indus Valley: Economy, Society, Religion'},
  {id:6,  sec:'ancient', topic:'Vedic Period: Rigvedic Age'},
  {id:7,  sec:'ancient', topic:'Later Vedic Period'},
  {id:8,  sec:'ancient', topic:'Mahajanapada Period'},
  {id:9,  sec:'ancient', topic:'Buddhism and Jainism'},
  {id:10, sec:'ancient', topic:'Mauryan Empire: Administration'},
  {id:11, sec:'ancient', topic:'Ashoka: Dhamma and Inscriptions'},
  {id:12, sec:'ancient', topic:'Mauryan Art and Architecture'},
  {id:13, sec:'ancient', topic:'Post-Mauryan Period'},
  {id:14, sec:'ancient', topic:'Gupta Administration'},
  {id:15, sec:'ancient', topic:'Gupta Period: Art and Science'},
  {id:16, sec:'ancient', topic:'Harsha Vardhana'},
  {id:17, sec:'ancient', topic:'South India: Cholas and Pallavas'},
  {id:18, sec:'ancient', topic:'Ancient Society and Economy'},
  {id:19, sec:'ancient', topic:'Revision + Map Work'},
  {id:20, sec:'ancient', topic:'Test + PYQs — Ancient History'},
  {id:21, sec:'medieval', topic:'Early Medieval Kingdoms'},
  {id:22, sec:'medieval', topic:'Rajputs: Rise and Culture'},
  {id:23, sec:'medieval', topic:'Arab and Turkish Invasions'},
  {id:24, sec:'medieval', topic:'Delhi Sultanate: Early Phase'},
  {id:25, sec:'medieval', topic:'Delhi Sultanate: Administration'},
  {id:26, sec:'medieval', topic:'Akbar: Administration'},
  {id:27, sec:'medieval', topic:'Akbar: Religious Policy'},
  {id:28, sec:'medieval', topic:'Jahangir and Shah Jahan'},
  {id:29, sec:'medieval', topic:'Aurangzeb'},
  {id:30, sec:'medieval', topic:'Mughal Decline'},
  {id:31, sec:'medieval', topic:'Maratha Administration'},
  {id:32, sec:'medieval', topic:'Bhakti Movement'},
  {id:33, sec:'medieval', topic:'Sufi Movement'},
  {id:34, sec:'medieval', topic:'Medieval Art and Architecture'},
  {id:35, sec:'medieval', topic:'Medieval Economy'},
  {id:36, sec:'medieval', topic:'States of South India'},
  {id:37, sec:'medieval', topic:'Society and Culture'},
  {id:38, sec:'medieval', topic:'Revision'},
  {id:39, sec:'medieval', topic:'Map Work + PYQs'},
  {id:40, sec:'medieval', topic:'Test: Medieval History'},
  {id:41, sec:'modern', topic:'Arrival of European Companies'},
  {id:42, sec:'modern', topic:'British Conquest: 1757–1764'},
  {id:43, sec:'modern', topic:'Company Rule'},
  {id:44, sec:'modern', topic:'Permanent Settlement'},
  {id:45, sec:'modern', topic:'Revolt of 1857'},
  {id:46, sec:'modern', topic:'Peasant Movements'},
  {id:47, sec:'modern', topic:'Tribal Movements'},
  {id:48, sec:'modern', topic:'Social-Religious Reform Movements'},
  {id:49, sec:'modern', topic:'Establishment of INC'},
  {id:50, sec:'modern', topic:'Moderates and Extremists'},
  {id:51, sec:'modern', topic:'Gandhi Era: Beginning'},
  {id:52, sec:'modern', topic:'Non-Cooperation Movement'},
  {id:53, sec:'modern', topic:'Civil Disobedience Movement'},
  {id:54, sec:'modern', topic:'Quit India Movement'},
  {id:55, sec:'modern', topic:'Constitution Making'},
  {id:56, sec:'modern', topic:'Independence and Partition'},
  {id:57, sec:'modern', topic:'Free India (Post-Independence)'},
  {id:58, sec:'modern', topic:'Timeline + Revision'},
  {id:59, sec:'modern', topic:'PYQs + Map Work'},
  {id:60, sec:'modern', topic:'Grand Test'},
  {id:61, sec:'polity', topic:'Constitution: Historical Background'},
  {id:62, sec:'polity', topic:'Features of the Constitution'},
  {id:63, sec:'polity', topic:'Making of the Constitution'},
  {id:64, sec:'polity', topic:'Preamble'},
  {id:65, sec:'polity', topic:'Union and Its Territory'},
  {id:66, sec:'polity', topic:'Citizenship'},
  {id:67, sec:'polity', topic:'Fundamental Rights'},
  {id:68, sec:'polity', topic:'Fundamental Duties'},
  {id:69, sec:'polity', topic:'Directive Principles of State Policy'},
  {id:70, sec:'polity', topic:'President'},
  {id:71, sec:'polity', topic:'Vice-President'},
  {id:72, sec:'polity', topic:'Prime Minister and Council of Ministers'},
  {id:73, sec:'polity', topic:'Parliament: Structure'},
  {id:74, sec:'polity', topic:'Parliament: Functions and Powers'},
  {id:75, sec:'polity', topic:'Polity Revision + PYQs'},
  {id:76, sec:'polity', topic:'Legislative Procedure'},
  {id:77, sec:'polity', topic:'Supreme Court'},
  {id:78, sec:'polity', topic:'High Court'},
  {id:79, sec:'polity', topic:'Judicial Review'},
  {id:80, sec:'polity', topic:'Centre-State Relations'},
  {id:81, sec:'polity', topic:'Governor'},
  {id:82, sec:'polity', topic:'Chief Minister and Council of Ministers'},
  {id:83, sec:'polity', topic:'State Legislature'},
  {id:84, sec:'polity', topic:'Panchayati Raj System'},
  {id:85, sec:'polity', topic:'Municipalities'},
  {id:86, sec:'polity', topic:'Constitutional Bodies'},
  {id:87, sec:'polity', topic:'Non-Constitutional Bodies'},
  {id:88, sec:'polity', topic:'Constitutional Amendments'},
  {id:89, sec:'polity', topic:'Emergency Provisions'},
  {id:90, sec:'polity', topic:'Full Polity Test + Revision'},
  {id:91,  sec:'bihar', topic:'Bihar Ancient History + Microeconomics'},
  {id:92,  sec:'bihar', topic:'Bihar Medieval History + Microeconomics'},
  {id:93,  sec:'bihar', topic:'Bihar Modern History + Demand and Supply'},
  {id:94,  sec:'bihar', topic:'Bihar Freedom Movement + National Income'},
  {id:95,  sec:'bihar', topic:'Bihar Physical Geography + Money and Banking'},
  {id:96,  sec:'bihar', topic:'Bihar Rivers and Soil + Inflation'},
  {id:97,  sec:'bihar', topic:'Bihar Economy Overview + Fiscal Policy'},
  {id:98,  sec:'bihar', topic:'Bihar Agriculture + Monetary Policy'},
  {id:99,  sec:'bihar', topic:'Bihar Industry and Resources + Planning'},
  {id:100, sec:'bihar', topic:'Bihar Administration + Indian Economy'},
  {id:101, sec:'bihar', topic:'Bihar Polity + Poverty and Unemployment'},
  {id:102, sec:'bihar', topic:'Bihar Government Schemes + Budget and Taxation'},
  {id:103, sec:'bihar', topic:'Bihar Current Issues + Economic Reforms'},
  {id:104, sec:'bihar', topic:'Bihar Culture + External Sector'},
  {id:105, sec:'bihar', topic:'Bihar Art and Heritage + Sustainable Dev'},
  {id:106, sec:'bihar', topic:'Bihar Disaster Management + Inclusive Growth'},
  {id:107, sec:'bihar', topic:'Bihar Census and Data + Economic Indicators'},
  {id:108, sec:'bihar', topic:'Bihar PYQs + Economics PYQs'},
  {id:109, sec:'bihar', topic:'Bihar Revision + Economics Revision'},
  {id:110, sec:'bihar', topic:'Bihar Test + Economics Test'},
  {id:111, sec:'maths', topic:'Bihar History (Rapid) + Number System'},
  {id:112, sec:'maths', topic:'Bihar Geography (Rapid) + Percentage'},
  {id:113, sec:'maths', topic:'Bihar Economy (Rapid) + Ratio and Proportion'},
  {id:114, sec:'maths', topic:'Bihar Polity and Admin + Profit and Loss'},
  {id:115, sec:'maths', topic:'Bihar Schemes and Issues + Average'},
  {id:116, sec:'maths', topic:'Bihar Culture + Time and Work'},
  {id:117, sec:'maths', topic:'Bihar Disaster Management + Time and Distance'},
  {id:118, sec:'maths', topic:'Bihar PYQs + Reasoning: Basics'},
  {id:119, sec:'maths', topic:'Bihar Full Revision + Reasoning: Practice'},
  {id:120, sec:'maths', topic:'Bihar Mock Test + Maths & Reasoning Mock'},
];
