// ─── REVISION SCHEDULE ──────────────────────────────────────────────────────
// User's actual schedule: from STUDY date (all absolute from study, not chained)
const REV_SCHEDULE = [
  { key: 'r1', label: 'R1', desc: 'Day +1',   days: 1  },
  { key: 'r2', label: 'R2', desc: 'Day +3',   days: 3  },
  { key: 'r3', label: 'R3', desc: 'Day +7',   days: 7  },
  { key: 'r4', label: 'R4', desc: 'Day +15',  days: 15 },
  { key: 'r5', label: 'R5', desc: 'Day +30',  days: 30 },
  { key: 'r6', label: 'R6', desc: 'Day +75',  days: 75 },
];

// ─── STUDY PLAN ─────────────────────────────────────────────────────────────
const STUDY_PLAN = {
  startDate: '2026-03-22',
  examDate:  '2026-07-26',
  graceDays: 5,
  phases: [
    {
      id: 'phase1', label: 'Phase 1', days: [1, 20], color: '#7B1F3A',
      desc: 'Ancient India (Days 1–20)',
      sections: ['ancient']
    },
    {
      id: 'phase2', label: 'Phase 2', days: [21, 40], color: '#1E5C38',
      desc: 'Medieval India (Days 21–40)',
      sections: ['medieval']
    },
    {
      id: 'phase3', label: 'Phase 3', days: [41, 60], color: '#0B4F8C',
      desc: 'Modern India (Days 41–60)',
      sections: ['modern']
    },
    {
      id: 'phase4', label: 'Phase 4', days: [61, 90], color: '#6B3FA0',
      desc: 'Polity + Geography (Days 61–90)',
      sections: ['polity']
    },
    {
      id: 'phase5', label: 'Phase 5', days: [91, 110], color: '#B07A00',
      desc: 'Bihar Special + Economics (Days 91–110)',
      sections: ['bihar']
    },
    {
      id: 'phase6', label: 'Phase 6', days: [111, 120], color: '#333333',
      desc: 'Maths + Reasoning (Days 111–120)',
      sections: ['maths']
    },
  ]
};

// ─── SECTIONS META ──────────────────────────────────────────────────────────
const SECTIONS_META = {
  science:  { label: 'General Science',    range: 'S1–S20', color: '#555555' },
  ancient:  { label: 'Ancient India',      range: '1–20',   color: '#7B1F3A' },
  medieval: { label: 'Medieval India',     range: '21–40',  color: '#1E5C38' },
  modern:   { label: 'Modern India',       range: '41–60',  color: '#0B4F8C' },
  polity:   { label: 'Polity + Geography', range: '61–90',  color: '#6B3FA0' },
  bihar:    { label: 'Bihar + Economics',  range: '91–110', color: '#B07A00' },
  maths:    { label: 'Maths + Reasoning',  range: '111–120',color: '#333333' },
};

// ─── SERIAL NUMBER TRACKER ──────────────────────────────────────────────────
// Tracks the highest numeric ID per section for sequential numbering of new topics
const SECTION_ID_COUNTERS = {
  science:  20,
  ancient:  20,
  medieval: 40,
  modern:   60,
  polity:   90,
  bihar:    110,
  maths:    120,
};

// ─── DAYS DATA ──────────────────────────────────────────────────────────────
// IMPORTANT: custom topics (added by user) are stored in IndexedDB, not here.
// They are loaded at runtime and injected into DAYS_DATA array.
const DAYS_DATA = [
  {id:'s1',  sec:'science', topic:'Matter, Sorting Materials', planDay: null},
  {id:'s2',  sec:'science', topic:'Light, Shadows, Electricity Basics', planDay: null},
  {id:'s3',  sec:'science', topic:'Living / Non-Living, Body Movement', planDay: null},
  {id:'s4',  sec:'science', topic:'Food: Sources, Components', planDay: null},
  {id:'s5',  sec:'science', topic:'Heat, Acids & Bases', planDay: null},
  {id:'s6',  sec:'science', topic:'Light, Electric Current', planDay: null},
  {id:'s7',  sec:'science', topic:'Weather, Wind, Water', planDay: null},
  {id:'s8',  sec:'science', topic:'Crop Production, Microorganisms', planDay: null},
  {id:'s9',  sec:'science', topic:'Coal, Petroleum, Combustion', planDay: null},
  {id:'s10', sec:'science', topic:'Cell Structure, Reproduction', planDay: null},
  {id:'s11', sec:'science', topic:'Force, Friction, Sound', planDay: null},
  {id:'s12', sec:'science', topic:'Matter — States, Changes', planDay: null},
  {id:'s13', sec:'science', topic:'Atoms, Molecules, Structure', planDay: null},
  {id:'s14', sec:'science', topic:'Motion, Force, Laws', planDay: null},
  {id:'s15', sec:'science', topic:'Work, Energy, Sound', planDay: null},
  {id:'s16', sec:'science', topic:'Life Processes, Control', planDay: null},
  {id:'s17', sec:'science', topic:'Heredity, Evolution', planDay: null},
  {id:'s18', sec:'science', topic:'Light, Electricity, Magnetic', planDay: null},
  {id:'s19', sec:'science', topic:'Carbon Compounds, Metals', planDay: null},
  {id:'s20', sec:'science', topic:'Test Science NCERT', planDay: null},
  {id:1,  sec:'ancient', topic:'Sources of History + Prehistoric Period', planDay:1},
  {id:2,  sec:'ancient', topic:'Palaeolithic and Mesolithic Age', planDay:2},
  {id:3,  sec:'ancient', topic:'Neolithic and Chalcolithic Age', planDay:3},
  {id:4,  sec:'ancient', topic:'Indus Valley: Town Planning', planDay:4},
  {id:5,  sec:'ancient', topic:'Indus Valley: Economy, Society, Religion', planDay:5},
  {id:6,  sec:'ancient', topic:'Vedic Period: Rigvedic Age', planDay:6},
  {id:7,  sec:'ancient', topic:'Later Vedic Period', planDay:7},
  {id:8,  sec:'ancient', topic:'Mahajanapada Period', planDay:8},
  {id:9,  sec:'ancient', topic:'Buddhism and Jainism', planDay:9},
  {id:10, sec:'ancient', topic:'Mauryan Empire: Administration', planDay:10},
  {id:11, sec:'ancient', topic:'Ashoka: Dhamma and Inscriptions', planDay:11},
  {id:12, sec:'ancient', topic:'Mauryan Art and Architecture', planDay:12},
  {id:13, sec:'ancient', topic:'Post-Mauryan Period', planDay:13},
  {id:14, sec:'ancient', topic:'Gupta Administration', planDay:14},
  {id:15, sec:'ancient', topic:'Gupta Period: Art and Science', planDay:15},
  {id:16, sec:'ancient', topic:'Harsha Vardhana', planDay:16},
  {id:17, sec:'ancient', topic:'South India: Cholas and Pallavas', planDay:17},
  {id:18, sec:'ancient', topic:'Ancient Society and Economy', planDay:18},
  {id:19, sec:'ancient', topic:'Revision + Map Work', planDay:19},
  {id:20, sec:'ancient', topic:'Test + PYQs — Ancient History', planDay:20},
  {id:21, sec:'medieval', topic:'Early Medieval Kingdoms', planDay:21},
  {id:22, sec:'medieval', topic:'Rajputs: Rise and Culture', planDay:22},
  {id:23, sec:'medieval', topic:'Arab and Turkish Invasions', planDay:23},
  {id:24, sec:'medieval', topic:'Delhi Sultanate: Early Phase', planDay:24},
  {id:25, sec:'medieval', topic:'Delhi Sultanate: Administration', planDay:25},
  {id:26, sec:'medieval', topic:'Akbar: Administration', planDay:26},
  {id:27, sec:'medieval', topic:'Akbar: Religious Policy', planDay:27},
  {id:28, sec:'medieval', topic:'Jahangir and Shah Jahan', planDay:28},
  {id:29, sec:'medieval', topic:'Aurangzeb', planDay:29},
  {id:30, sec:'medieval', topic:'Mughal Decline', planDay:30},
  {id:31, sec:'medieval', topic:'Maratha Administration', planDay:31},
  {id:32, sec:'medieval', topic:'Bhakti Movement', planDay:32},
  {id:33, sec:'medieval', topic:'Sufi Movement', planDay:33},
  {id:34, sec:'medieval', topic:'Medieval Art and Architecture', planDay:34},
  {id:35, sec:'medieval', topic:'Medieval Economy', planDay:35},
  {id:36, sec:'medieval', topic:'States of South India', planDay:36},
  {id:37, sec:'medieval', topic:'Society and Culture', planDay:37},
  {id:38, sec:'medieval', topic:'Revision', planDay:38},
  {id:39, sec:'medieval', topic:'Map Work + PYQs', planDay:39},
  {id:40, sec:'medieval', topic:'Test: Medieval History', planDay:40},
  {id:41, sec:'modern', topic:'Arrival of European Companies', planDay:41},
  {id:42, sec:'modern', topic:'British Conquest: 1757–1764', planDay:42},
  {id:43, sec:'modern', topic:'Company Rule', planDay:43},
  {id:44, sec:'modern', topic:'Permanent Settlement', planDay:44},
  {id:45, sec:'modern', topic:'Revolt of 1857', planDay:45},
  {id:46, sec:'modern', topic:'Peasant Movements', planDay:46},
  {id:47, sec:'modern', topic:'Tribal Movements', planDay:47},
  {id:48, sec:'modern', topic:'Social-Religious Reform Movements', planDay:48},
  {id:49, sec:'modern', topic:'Establishment of INC', planDay:49},
  {id:50, sec:'modern', topic:'Moderates and Extremists', planDay:50},
  {id:51, sec:'modern', topic:'Gandhi Era: Beginning', planDay:51},
  {id:52, sec:'modern', topic:'Non-Cooperation Movement', planDay:52},
  {id:53, sec:'modern', topic:'Civil Disobedience Movement', planDay:53},
  {id:54, sec:'modern', topic:'Quit India Movement', planDay:54},
  {id:55, sec:'modern', topic:'Constitution Making', planDay:55},
  {id:56, sec:'modern', topic:'Independence and Partition', planDay:56},
  {id:57, sec:'modern', topic:'Free India (Post-Independence)', planDay:57},
  {id:58, sec:'modern', topic:'Timeline + Revision', planDay:58},
  {id:59, sec:'modern', topic:'PYQs + Map Work', planDay:59},
  {id:60, sec:'modern', topic:'Grand Test', planDay:60},
  {id:61, sec:'polity', topic:'Constitution: Historical Background', planDay:61},
  {id:62, sec:'polity', topic:'Features of the Constitution', planDay:62},
  {id:63, sec:'polity', topic:'Making of the Constitution', planDay:63},
  {id:64, sec:'polity', topic:'Preamble', planDay:64},
  {id:65, sec:'polity', topic:'Union and Its Territory', planDay:65},
  {id:66, sec:'polity', topic:'Citizenship', planDay:66},
  {id:67, sec:'polity', topic:'Fundamental Rights', planDay:67},
  {id:68, sec:'polity', topic:'Fundamental Duties', planDay:68},
  {id:69, sec:'polity', topic:'Directive Principles of State Policy', planDay:69},
  {id:70, sec:'polity', topic:'President', planDay:70},
  {id:71, sec:'polity', topic:'Vice-President', planDay:71},
  {id:72, sec:'polity', topic:'Prime Minister and Council of Ministers', planDay:72},
  {id:73, sec:'polity', topic:'Parliament: Structure', planDay:73},
  {id:74, sec:'polity', topic:'Parliament: Functions and Powers', planDay:74},
  {id:75, sec:'polity', topic:'Polity Revision + PYQs', planDay:75},
  {id:76, sec:'polity', topic:'Legislative Procedure', planDay:76},
  {id:77, sec:'polity', topic:'Supreme Court', planDay:77},
  {id:78, sec:'polity', topic:'High Court', planDay:78},
  {id:79, sec:'polity', topic:'Judicial Review', planDay:79},
  {id:80, sec:'polity', topic:'Centre-State Relations', planDay:80},
  {id:81, sec:'polity', topic:'Governor', planDay:81},
  {id:82, sec:'polity', topic:'Chief Minister and Council of Ministers', planDay:82},
  {id:83, sec:'polity', topic:'State Legislature', planDay:83},
  {id:84, sec:'polity', topic:'Panchayati Raj System', planDay:84},
  {id:85, sec:'polity', topic:'Municipalities', planDay:85},
  {id:86, sec:'polity', topic:'Constitutional Bodies', planDay:86},
  {id:87, sec:'polity', topic:'Non-Constitutional Bodies', planDay:87},
  {id:88, sec:'polity', topic:'Constitutional Amendments', planDay:88},
  {id:89, sec:'polity', topic:'Emergency Provisions', planDay:89},
  {id:90, sec:'polity', topic:'Full Polity Test + Revision', planDay:90},
  {id:91,  sec:'bihar', topic:'Bihar Ancient History + Microeconomics', planDay:91},
  {id:92,  sec:'bihar', topic:'Bihar Medieval History + Microeconomics', planDay:92},
  {id:93,  sec:'bihar', topic:'Bihar Modern History + Demand and Supply', planDay:93},
  {id:94,  sec:'bihar', topic:'Bihar Freedom Movement + National Income', planDay:94},
  {id:95,  sec:'bihar', topic:'Bihar Physical Geography + Money and Banking', planDay:95},
  {id:96,  sec:'bihar', topic:'Bihar Rivers and Soil + Inflation', planDay:96},
  {id:97,  sec:'bihar', topic:'Bihar Economy Overview + Fiscal Policy', planDay:97},
  {id:98,  sec:'bihar', topic:'Bihar Agriculture + Monetary Policy', planDay:98},
  {id:99,  sec:'bihar', topic:'Bihar Industry and Resources + Planning', planDay:99},
  {id:100, sec:'bihar', topic:'Bihar Administration + Indian Economy', planDay:100},
  {id:101, sec:'bihar', topic:'Bihar Polity + Poverty and Unemployment', planDay:101},
  {id:102, sec:'bihar', topic:'Bihar Government Schemes + Budget and Taxation', planDay:102},
  {id:103, sec:'bihar', topic:'Bihar Current Issues + Economic Reforms', planDay:103},
  {id:104, sec:'bihar', topic:'Bihar Culture + External Sector', planDay:104},
  {id:105, sec:'bihar', topic:'Bihar Art and Heritage + Sustainable Dev', planDay:105},
  {id:106, sec:'bihar', topic:'Bihar Disaster Management + Inclusive Growth', planDay:106},
  {id:107, sec:'bihar', topic:'Bihar Census and Data + Economic Indicators', planDay:107},
  {id:108, sec:'bihar', topic:'Bihar PYQs + Economics PYQs', planDay:108},
  {id:109, sec:'bihar', topic:'Bihar Revision + Economics Revision', planDay:109},
  {id:110, sec:'bihar', topic:'Bihar Test + Economics Test', planDay:110},
  {id:111, sec:'maths', topic:'Bihar History (Rapid) + Number System', planDay:111},
  {id:112, sec:'maths', topic:'Bihar Geography (Rapid) + Percentage', planDay:112},
  {id:113, sec:'maths', topic:'Bihar Economy (Rapid) + Ratio and Proportion', planDay:113},
  {id:114, sec:'maths', topic:'Bihar Polity and Admin + Profit and Loss', planDay:114},
  {id:115, sec:'maths', topic:'Bihar Schemes and Issues + Average', planDay:115},
  {id:116, sec:'maths', topic:'Bihar Culture + Time and Work', planDay:116},
  {id:117, sec:'maths', topic:'Bihar Disaster Management + Time and Distance', planDay:117},
  {id:118, sec:'maths', topic:'Bihar PYQs + Reasoning: Basics', planDay:118},
  {id:119, sec:'maths', topic:'Bihar Full Revision + Reasoning: Practice', planDay:119},
  {id:120, sec:'maths', topic:'Bihar Mock Test + Maths & Reasoning Mock', planDay:120},
];
