// ─── BPSC TRACKER v3 · data.js ───────────────────────────────────────────────

const REV_SCHEDULE = [
  { key: 'r1', label: 'R1', gap: 1,  desc: '+1d'  },
  { key: 'r2', label: 'R2', gap: 2,  desc: '+2d'  },
  { key: 'r3', label: 'R3', gap: 4,  desc: '+4d'  },
  { key: 'r4', label: 'R4', gap: 7,  desc: '+7d'  },
  { key: 'r5', label: 'R5', gap: 10, desc: '+10d' },
  { key: 'r6', label: 'R6', gap: 14, desc: '+14d' },
  { key: 'r7', label: 'R7', gap: 18, desc: '+18d' },
  { key: 'r8', label: 'R8', gap: 21, desc: '+21d' },
];

const STUDY_PLAN = {
  startDate: '2026-03-22',
  examDate:  '2026-07-26',
  graceDays: 5,
  phases: [
    {
      id: 'p1', label: 'Phase 1',
      days: [1, 49],
      sections: ['ancient', 'medieval', 'modern', 'science', 'bihar', 'ca_p1'],
      color: '#7B1F3A',
      desc: 'Ancient · Medieval · Modern · Science · Bihar'
    },
    {
      id: 'p2', label: 'Phase 2',
      days: [50, 74],
      sections: ['polity', 'geography', 'ca_p2'],
      color: '#1E5C38',
      desc: 'Polity · Geography · CA Apr–May 26'
    },
    {
      id: 'p3', label: 'Phase 3',
      days: [75, 90],
      sections: ['economy', 'maths', 'ca_p3'],
      color: '#0B4F8C',
      desc: 'Economy · Maths · CA Jun–Jul 26'
    }
  ]
};

const SECTIONS_META = {
  science:   { label: 'General Science',      color: '#555555' },
  ancient:   { label: 'Ancient India',         color: '#7B1F3A' },
  medieval:  { label: 'Medieval India',        color: '#1E5C38' },
  modern:    { label: 'Modern India',          color: '#0B4F8C' },
  bihar:     { label: 'Bihar Special',         color: '#B07A00' },
  polity:    { label: 'Polity',                color: '#6B3FA0' },
  geography: { label: 'Geography',             color: '#2E8B57' },
  economy:   { label: 'Economics',             color: '#8B4513' },
  maths:     { label: 'Maths & Reasoning',     color: '#333333' },
  ca_p1:     { label: 'CA Jun 25–Mar 26',      color: '#D2691E' },
  ca_p2:     { label: 'CA Apr–May 26',         color: '#FF4500' },
  ca_p3:     { label: 'CA Jun–Jul 26',         color: '#CC0000' },
};

const DAYS_DATA = [
  // ── PHASE 1 · DAYS 1–20 (Ancient + Science) ──────────────────────────────
  { id: 's1',  sec: 'science', topic: 'Matter, Sorting Materials',               planDay: 1  },
  { id: '1',   sec: 'ancient', topic: 'Sources of History + Prehistoric Period', planDay: 1  },
  { id: 's2',  sec: 'science', topic: 'Light, Shadows, Electricity Basics',      planDay: 2  },
  { id: '2',   sec: 'ancient', topic: 'Palaeolithic and Mesolithic Age',          planDay: 2  },
  { id: 's3',  sec: 'science', topic: 'Living / Non-Living, Body Movement',      planDay: 3  },
  { id: '3',   sec: 'ancient', topic: 'Neolithic and Chalcolithic Age',           planDay: 3  },
  { id: 's4',  sec: 'science', topic: 'Food: Sources, Components',               planDay: 4  },
  { id: '4',   sec: 'ancient', topic: 'Indus Valley: Town Planning',             planDay: 4  },
  { id: 's5',  sec: 'science', topic: 'Heat, Acids & Bases',                     planDay: 5  },
  { id: '5',   sec: 'ancient', topic: 'Indus Valley: Economy, Society, Religion',planDay: 5  },
  { id: 's6',  sec: 'science', topic: 'Light, Electric Current',                 planDay: 6  },
  { id: '6',   sec: 'ancient', topic: 'Vedic Period: Rigvedic Age',              planDay: 6  },
  { id: 's7',  sec: 'science', topic: 'Weather, Wind, Water',                    planDay: 7  },
  { id: '7',   sec: 'ancient', topic: 'Later Vedic Period',                      planDay: 7  },
  { id: 's8',  sec: 'science', topic: 'Crop Production, Microorganisms',         planDay: 8  },
  { id: '8',   sec: 'ancient', topic: 'Mahajanapada Period',                     planDay: 8  },
  { id: 's9',  sec: 'science', topic: 'Coal, Petroleum, Combustion',             planDay: 9  },
  { id: '9',   sec: 'ancient', topic: 'Buddhism and Jainism',                    planDay: 9  },
  { id: 's10', sec: 'science', topic: 'Cell Structure, Reproduction',            planDay: 10 },
  { id: '10',  sec: 'ancient', topic: 'Mauryan Empire: Administration',           planDay: 10 },
  { id: 's11', sec: 'science', topic: 'Force, Friction, Sound',                  planDay: 11 },
  { id: '11',  sec: 'ancient', topic: 'Ashoka: Dhamma and Inscriptions',         planDay: 11 },
  { id: 's12', sec: 'science', topic: 'Matter — States, Changes',                planDay: 12 },
  { id: '12',  sec: 'ancient', topic: 'Mauryan Art and Architecture',            planDay: 12 },
  { id: 's13', sec: 'science', topic: 'Atoms, Molecules, Structure',             planDay: 13 },
  { id: '13',  sec: 'ancient', topic: 'Post-Mauryan Period',                     planDay: 13 },
  { id: 's14', sec: 'science', topic: 'Motion, Force, Laws',                     planDay: 14 },
  { id: '14',  sec: 'ancient', topic: 'Gupta Administration',                    planDay: 14 },
  { id: 's15', sec: 'science', topic: 'Work, Energy, Sound',                     planDay: 15 },
  { id: '15',  sec: 'ancient', topic: 'Gupta Period: Art and Science',           planDay: 15 },
  { id: 's16', sec: 'science', topic: 'Life Processes, Control',                 planDay: 16 },
  { id: '16',  sec: 'ancient', topic: 'Harsha Vardhana',                         planDay: 16 },
  { id: 's17', sec: 'science', topic: 'Heredity, Evolution',                     planDay: 17 },
  { id: '17',  sec: 'ancient', topic: 'South India: Cholas and Pallavas',        planDay: 17 },
  { id: 's18', sec: 'science', topic: 'Light, Electricity, Magnetic',            planDay: 18 },
  { id: '18',  sec: 'ancient', topic: 'Ancient Society and Economy',             planDay: 18 },
  { id: 's19', sec: 'science', topic: 'Carbon Compounds, Metals',                planDay: 19 },
  { id: '19',  sec: 'ancient', topic: 'Revision + Map Work',                     planDay: 19 },
  { id: 's20', sec: 'science', topic: 'Test Science NCERT',                      planDay: 20 },
  { id: '20',  sec: 'ancient', topic: 'Test + PYQs — Ancient History',           planDay: 20 },

  // ── PHASE 1 · DAYS 21–35 (Medieval + Bihar) ──────────────────────────────
  { id: '21',  sec: 'medieval', topic: 'Early Medieval Kingdoms',                  planDay: 21 },
  { id: '91',  sec: 'bihar',    topic: 'Bihar Ancient History + Micro',            planDay: 21 },
  { id: '22',  sec: 'medieval', topic: 'Rajputs: Rise and Culture',                planDay: 22 },
  { id: '92',  sec: 'bihar',    topic: 'Bihar Medieval History + Micro',           planDay: 22 },
  { id: '23',  sec: 'medieval', topic: 'Arab and Turkish Invasions',               planDay: 23 },
  { id: '93',  sec: 'bihar',    topic: 'Bihar Modern History + Demand/Supply',     planDay: 23 },
  { id: '24',  sec: 'medieval', topic: 'Delhi Sultanate: Early Phase',             planDay: 24 },
  { id: '94',  sec: 'bihar',    topic: 'Bihar Freedom Movement + National Income', planDay: 24 },
  { id: '25',  sec: 'medieval', topic: 'Delhi Sultanate: Administration',          planDay: 25 },
  { id: '95',  sec: 'bihar',    topic: 'Bihar Physical Geography + Banking',       planDay: 25 },
  { id: '26',  sec: 'medieval', topic: 'Akbar: Administration',                    planDay: 26 },
  { id: '96',  sec: 'bihar',    topic: 'Bihar Rivers and Soil + Inflation',        planDay: 26 },
  { id: '27',  sec: 'medieval', topic: 'Akbar: Religious Policy',                  planDay: 27 },
  { id: '97',  sec: 'bihar',    topic: 'Bihar Economy Overview + Fiscal Policy',   planDay: 27 },
  { id: '28',  sec: 'medieval', topic: 'Jahangir and Shah Jahan',                  planDay: 28 },
  { id: '98',  sec: 'bihar',    topic: 'Bihar Agriculture + Monetary Policy',      planDay: 28 },
  { id: '29',  sec: 'medieval', topic: 'Aurangzeb',                                planDay: 29 },
  { id: '99',  sec: 'bihar',    topic: 'Bihar Industry & Planning',                planDay: 29 },
  { id: '30',  sec: 'medieval', topic: 'Mughal Decline',                           planDay: 30 },
  { id: '100', sec: 'bihar',    topic: 'Bihar Administration + Indian Economy',    planDay: 30 },
  { id: '31',  sec: 'medieval', topic: 'Maratha Administration',                   planDay: 31 },
  { id: '101', sec: 'bihar',    topic: 'Bihar Polity + Poverty',                   planDay: 31 },
  { id: '32',  sec: 'medieval', topic: 'Bhakti & Sufi Movement',                   planDay: 32 },
  { id: '102', sec: 'bihar',    topic: 'Bihar Govt Schemes + Taxation',            planDay: 32 },
  { id: '34',  sec: 'medieval', topic: 'Medieval Art & Architecture',              planDay: 33 },
  { id: '103', sec: 'bihar',    topic: 'Bihar Current Issues + Reforms',           planDay: 33 },
  { id: '36',  sec: 'medieval', topic: 'South India States & Economy',             planDay: 34 },
  { id: '105', sec: 'bihar',    topic: 'Bihar Art & Heritage + Sustainable Dev',   planDay: 34 },
  { id: '40',  sec: 'medieval', topic: 'Test: Medieval History',                   planDay: 35 },
  { id: '110', sec: 'bihar',    topic: 'Bihar Test + Economics Test',              planDay: 35 },

  // ── PHASE 1 · DAYS 36–49 (Modern + CA P1) ────────────────────────────────
  { id: '41',    sec: 'modern', topic: 'Arrival of European Companies',             planDay: 36 },
  { id: '42',    sec: 'modern', topic: 'British Conquest: 1757–1764',               planDay: 37 },
  { id: '43',    sec: 'modern', topic: 'Company Rule & Permanent Settlement',       planDay: 38 },
  { id: '45',    sec: 'modern', topic: 'Revolt of 1857',                            planDay: 39 },
  { id: '46',    sec: 'modern', topic: 'Peasant & Tribal Movements',                planDay: 40 },
  { id: '48',    sec: 'modern', topic: 'Social-Religious Reform Movements',         planDay: 41 },
  { id: '49',    sec: 'modern', topic: 'Establishment of INC & Moderates',          planDay: 42 },
  { id: '50',    sec: 'modern', topic: 'Extremists & Gandhi Era Beginning',         planDay: 43 },
  { id: '52',    sec: 'modern', topic: 'Non-Cooperation & Civil Disobedience',      planDay: 44 },
  { id: '54',    sec: 'modern', topic: 'Quit India Movement',                       planDay: 45 },
  { id: '55',    sec: 'modern', topic: 'Constitution Making & Partition',           planDay: 46 },
  { id: '57',    sec: 'modern', topic: 'Post-Independence & Timeline',              planDay: 47 },
  { id: '59',    sec: 'modern', topic: 'PYQs + Map Work',                           planDay: 48 },
  { id: '60',    sec: 'modern', topic: 'Grand Test: Modern History',                planDay: 49 },
  { id: 'ca1_f', sec: 'ca_p1', topic: 'CA Comprehensive: Jun 25 – Mar 26',         planDay: 49 },

  // ── PHASE 2 · DAYS 50–74 (Polity + Geography + CA P2) ────────────────────
  { id: '61',    sec: 'polity',    topic: 'Historical Background & Features',       planDay: 50 },
  { id: 'g1',    sec: 'geography', topic: 'Geomorphology: Interior of Earth',       planDay: 50 },
  { id: '63',    sec: 'polity',    topic: 'Making of Constitution & Preamble',      planDay: 51 },
  { id: 'g2',    sec: 'geography', topic: 'Climatology: Atmosphere & Winds',        planDay: 51 },
  { id: '65',    sec: 'polity',    topic: 'Union & Citizenship',                    planDay: 52 },
  { id: 'g3',    sec: 'geography', topic: 'Oceanography: Currents & Tides',         planDay: 52 },
  { id: '67',    sec: 'polity',    topic: 'Fundamental Rights',                     planDay: 53 },
  { id: 'g4',    sec: 'geography', topic: 'Indian Physiography: Mountains',         planDay: 53 },
  { id: '68',    sec: 'polity',    topic: 'DPSP & Fundamental Duties',              planDay: 54 },
  { id: 'g5',    sec: 'geography', topic: 'Drainage System: Rivers of India',       planDay: 54 },
  { id: '70',    sec: 'polity',    topic: 'President & Vice-President',             planDay: 55 },
  { id: '72',    sec: 'polity',    topic: 'PM & Council of Ministers',              planDay: 56 },
  { id: '73',    sec: 'polity',    topic: 'Parliament Structure & Functions',       planDay: 57 },
  { id: '76',    sec: 'polity',    topic: 'Legislative Procedure',                  planDay: 58 },
  { id: '77',    sec: 'polity',    topic: 'Supreme Court & High Court',             planDay: 59 },
  { id: '79',    sec: 'polity',    topic: 'Judicial Review & Centre-State',         planDay: 60 },
  { id: '81',    sec: 'polity',    topic: 'Governor & CM',                          planDay: 61 },
  { id: '83',    sec: 'polity',    topic: 'State Legislature',                      planDay: 62 },
  { id: '84',    sec: 'polity',    topic: 'Panchayati Raj & Municipalities',        planDay: 63 },
  { id: '86',    sec: 'polity',    topic: 'Constitutional Bodies',                  planDay: 64 },
  { id: '87',    sec: 'polity',    topic: 'Non-Constitutional Bodies',              planDay: 65 },
  { id: '88',    sec: 'polity',    topic: 'Amendments & Emergency',                 planDay: 66 },
  { id: '90',    sec: 'polity',    topic: 'Full Polity Test',                       planDay: 67 },
  { id: 'g6',    sec: 'geography', topic: 'Soil, Vegetation & Agriculture',         planDay: 68 },
  { id: 'g7',    sec: 'geography', topic: 'Minerals & Industries',                  planDay: 69 },
  { id: 'g8',    sec: 'geography', topic: 'World Geography: Continents',            planDay: 70 },
  { id: 'g9',    sec: 'geography', topic: 'Map Work: India & World',                planDay: 71 },
  { id: 'g10',   sec: 'geography', topic: 'Geography PYQs & Test',                  planDay: 72 },
  { id: 'ca2_1', sec: 'ca_p2',    topic: 'CA April 2026',                           planDay: 73 },
  { id: 'ca2_2', sec: 'ca_p2',    topic: 'CA May 2026',                             planDay: 74 },

  // ── PHASE 3 · DAYS 75–90 (Maths + CA P3) ────────────────────────────────
  { id: '111',      sec: 'maths', topic: 'Number System & Simplification',   planDay: 75 },
  { id: '112',      sec: 'maths', topic: 'Percentage & Average',             planDay: 76 },
  { id: '113',      sec: 'maths', topic: 'Ratio & Proportion',               planDay: 77 },
  { id: '114',      sec: 'maths', topic: 'Profit & Loss',                    planDay: 78 },
  { id: '116',      sec: 'maths', topic: 'Time & Work',                      planDay: 79 },
  { id: '117',      sec: 'maths', topic: 'Time & Distance',                  planDay: 80 },
  { id: '118',      sec: 'maths', topic: 'Reasoning: Coding-Decoding',       planDay: 81 },
  { id: 'r_118_1',  sec: 'maths', topic: 'Reasoning: Blood Relations',       planDay: 82 },
  { id: 'r_118_2',  sec: 'maths', topic: 'Reasoning: Syllogism',             planDay: 83 },
  { id: '119',      sec: 'maths', topic: 'Reasoning: Practice Set',          planDay: 84 },
  { id: '120',      sec: 'maths', topic: 'Maths & Reasoning Mock',           planDay: 85 },
  { id: 'ca3_1',    sec: 'ca_p3', topic: 'CA June 2026',                     planDay: 86 },
  { id: 'ca3_2',    sec: 'ca_p3', topic: 'CA July 2026 (Till Date)',         planDay: 87 },
  { id: 'rev_1',    sec: 'modern', topic: 'High-Yield Revision: Modern',     planDay: 88 },
  { id: 'rev_2',    sec: 'bihar',  topic: 'High-Yield Revision: Bihar',      planDay: 89 },
  { id: 'mock_final', sec: 'maths', topic: 'Full Length Mock Test',          planDay: 90 },
];

// Section ID counters for custom topic numbering
const SECTION_ID_COUNTERS = {
  science:   20,
  ancient:   20,
  medieval:  40,
  modern:    60,
  polity:    90,
  bihar:     110,
  maths:     120,
  geography: 150,
  economy:   200,
  ca_p1:     1000,
  ca_p2:     1100,
  ca_p3:     1200,
};
